version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: dockerfile/frontend.dev.dockerfile
    ports:
      - '3000:3000'
    volumes: 
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
